management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
        - bus-refresh
        - beans
        - env
catalogo-reforma-fiscal:
  regimenes:
    - 
      clave: "601"
      regimenFiscal: "General de Ley Personas Morales"
      tipo: "Física" 
    - 
      clave: "603"
      regimenFiscal: "Personas Morales con Fines no Lucrativos"
      tipo: "Física"
    - 
      clave: "605"
      regimenFiscal: "Sueldos y Salarios e Ingresos Asimilados a Salarios"
      tipo: "Física"
    - 
      clave: "606"
      regimenFiscal: "Arrendamiento"
      tipo: "Física"
    - 
      clave: "607"
      regimenFiscal: "Régimen de Enajenación o Adquisición de Bienes"
      tipo: "Física"
    - 
      clave: "608"
      regimenFiscal: "Demás ingresos"
      tipo: "Física"
    - 
      clave: "610"
      regimenFiscal: "Residentes en el Extranjero sin Establecimiento Permanente en México"
      tipo: "Física"
    - 
      clave: "611"
      regimenFiscal: "Ingresos por Dividendos (socios y accionistas)"
      tipo: "Física"
    - 
      clave: "612"
      regimenFiscal: "Personas Físicas con Actividades Empresariales y Profesionales"
      tipo: "Física"
    - 
      clave: "614"
      regimenFiscal: "Ingresos por intereses"
      tipo: "Física"
    - 
      clave: "615"
      regimenFiscal: "Régimen de los ingresos por obtención de premios"
      tipo: "Física"
    - 
      clave: "616"
      regimenFiscal: "Sin obligaciones fiscales"
      tipo: "Física"
    - 
      clave: "620"
      regimenFiscal: "Sociedades Cooperativas de Producción que optan por diferir sus ingresos"
      tipo: "Física"
    - 
      clave: "621"
      regimenFiscal: "Incorporación Fiscal"
      tipo: "Moral"
    - 
      clave: "622"
      regimenFiscal: "Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras"
      tipo: "Moral"
    - 
      clave: "623"
      regimenFiscal: "Opcional para Grupos de Sociedades"
      tipo: "Moral"
    - 
      clave: "624"
      regimenFiscal: "Coordinados"
      tipo: "Moral"
    - 
      clave: "625"
      regimenFiscal: "Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas"
      tipo: "Moral"
    - 
      clave: "626"
      regimenFiscal: "Régimen Simplificado de Confianza"
      tipo: "Moral"
spring:
  cloud:
    gcp:
      sql:
        database-name: quattro00011
        instance-connection-name: sio4-168120:us-central1:db-skynet
  application:
    name: multi-tenant-app
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: false
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/