spring:
  datasource:
    hikari:
      minimumIdle: 15
      maximumPoolSize: 80
      connectionTimeout: 60000
server:
  port: 8080  
webhook-id: 62
gateway-url: "https://api.quattrocrm.mx"
serviceUrl:
  quattro-upload:
    baseURL: https://quattro-upload-hnwaodlfja-uc.a.run.app
  quattro-poliza:
    baseURL: https://quattro-poliza-hnwaodlfja-uc.a.run.app
  quattro-crm:
    baseURL: "https://quattro-crm-hnwaodlfja-uc.a.run.app"  
  quattro-utilerias-api:
    baseURL: https://quattro-utilerias-api-hnwaodlfja-uc.a.run.app
  quattro-external-api:  
    baseURL: https://quattro-external-api-hnwaodlfja-uc.a.run.app
userlogin:
  autorization:
    username: 5fw1y-q0477-r0gKx-8CcGh-vTJdh
    password: Jr0QPbS5L7Bui7UfIiNNxVqTd3c8Ep1aAwzmK6owDkzDh__xUe-l
userproxy:
  token:
    username: Io77z-cB2OL-fFPw9-4s5MD-Eiex1
    password: Alh1a18hGbslio0axcRt4kLmMbto0WjdcE36gy5vllf6s5S8EnoaT2ie__m01-cZi
#Produccion
tenants:
  default-instance: "quattrocrm-db7"
  default-db: "quattro00398"
  datasources:
    "quattrocrm-db7":
      jdbcUrl: jdbc:mysql://10.46.32.3:3306/quattro00398?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "vjDT5qrievY70"
      databaseName: quattro00398