spring:
  datasource:
    hikari:
      minimumIdle: 15
      maximumPoolSize: 80
      connectionTimeout: 60000  
webhook-id: 62
gateway-url: "https://api.quattrocrm.mx"
serviceUrl:
  quattro-upload:
    baseURL: http://quattro-upload:8080
  quattro-poliza:
    baseURL: http://quattro-poliza:8080
  quattro-crm:
    baseURL: "http://quattro-crm:8080"  
  quattro-utilerias-api:
    baseURL: http://quattro-utilerias-api:8080
  quattro-external-api:  
    baseURL: http://quattro-external-api:8080
userlogin:
  autorization:
    username: 5fw1y-q0477-r0gKx-8CcGh-vTJdh
    password: Jr0QPbS5L7Bui7UfIiNNxVqTd3c8Ep1aAwzmK6owDkzDh__xUe-l
userproxy:
  token:
    username: Io77z-cB2OL-fFPw9-4s5MD-Eiex1
    password: Alh1a18hGbslio0axcRt4kLmMbto0WjdcE36gy5vllf6s5S8EnoaT2ie__m01-cZi
#Produccion
tenants:
  default-instance: "quattrocrm-db1-v1"
  default-db: "quattro00060"
  datasources:
    "quattrocrm-db1-v1":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00001?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00001
    "quattrocrm-db2-v1":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00031?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00031
    "quattrocrm-db3":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00081?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00081
    "quattrocrm-db4":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00011?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00011
    "quattrocrm-db5":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00161?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00161
    "quattrocrm-db6":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00241?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00241
    "quattrocrm-db7":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00321?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00321
    "quattrocrm-db8":
      jdbcUrl: jdbc:mysql://${DB_HOST}/quattro00022?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      databaseName: quattro00022