webhook-id: 43
serviceUrl:
  quattro-upload:
    baseURL: https://quattro-upload-afa5eqprsa-uc.a.run.app
  quattro-crm:
    baseURL: "https://quattro-crm-afa5eqprsa-uc.a.run.app"
userlogin:
  autorization:
    username: 5fw1y-q0477-r0gKx-8CcGh-vTJdh
    password: Jr0QPbS5L7Bui7UfIiNNxVqTd3c8Ep1aAwzmK6owDkzDh__xUe-l
userproxy:
  token:
    username: Io77z-cB2OL-fFPw9-4s5MD-Eiex1
    password: Alh1a18hGbslio0axcRt4kLmMbto0WjdcE36gy5vllf6s5S8EnoaT2ie__m01-cZi
#QA 
tenants:
  datasources:
    "db-skynet":
      jdbcUrl: jdbc:mysql://10.2.112.234:3306/quattro00031?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "copsis123"
      databaseName: quattro00011
    "sio4rd":
      jdbcUrl: jdbc:mysql://10.2.112.3:3306/quattro00031?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "copsis123"
      databaseName: quattro00031