server:
  port: 8087
webhook-id: 43
gateway-url: "http://localhost:443"
serviceUrl:
  quattro-upload:
    baseURL: http://127.0.0.1:8080
  quattro-poliza:
    baseURL: "http://localhost:8082"
  quattro-crm:
    baseURL: "http://localhost:8093"
  quattro-utilerias-api:
    baseURL: http://localhost:8088
  quattro-external-api:  
    baseURL: http://localhost:8085
userlogin:
  autorization:
    username: 5fw1y-q0477-r0gKx-8CcGh-vTJdh
    password: Jr0QPbS5L7Bui7UfIiNNxVqTd3c8Ep1aAwzmK6owDkzDh__xUe-l
userproxy:
  token:
    username: Io77z-cB2OL-fFPw9-4s5MD-Eiex1
    password: Alh1a18hGbslio0axcRt4kLmMbto0WjdcE36gy5vllf6s5S8EnoaT2ie__m01-cZi
#QA y Produccion
tenants:
  datasources:
    "quattro-db1":
      jdbcUrl: jdbc:mysql://127.0.0.1:3309/webDB?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E#"
      databaseName: webDB
    "quattrocrm-db1-v1":
      jdbcUrl: jdbc:mysql://127.0.0.1:3311/quattro00001?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E#"
      databaseName: quattro00001
    "quattrocrm-db2-v1":
      jdbcUrl: jdbc:mysql://127.0.0.1:3312/quattro00031?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E#"
      databaseName: quattro00031
    "quattrocrm-db3":
      jdbcUrl: jdbc:mysql://127.0.0.1:3313/quattro00081?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E#"
      databaseName: quattro00081
    "quattrocrm-db4":
      jdbcUrl: jdbc:mysql://127.0.0.1:3314/quattro00011?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E#"
      databaseName: quattro00011
    "quattrocrm-db5":
      jdbcUrl: jdbc:mysql://127.0.0.1:3315/quattro00161?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E$"
      databaseName: quattro00161
    "quattrocrm-db6":
      jdbcUrl: jdbc:mysql://127.0.0.1:3316/quattro00241?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E$"
      databaseName: quattro00241
    "quattrocrm-db7":
      jdbcUrl: jdbc:mysql://127.0.0.1:3317/quattro00321?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E$"
      databaseName: quattro00321
    "quattrocrm-db8":
      jdbcUrl: jdbc:mysql://127.0.0.1:3318/quattro00022?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "cop$i$12E$"
      databaseName: quattro00022
    "db-skynet":
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/quattro00031?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "copsis123"
      databaseName: quattro00011
    "sio4rd":
      jdbcUrl: jdbc:mysql://127.0.0.1:3307/quattro00031?allowPublicKeyRetrieval=true&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: "copsis123"
      databaseName: quattro00031