management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
        - bus-refresh
        - beans
        - env
spring:
  cloud:
    gcp:
      sql:
        database-name: quattro00011
        instance-connection-name: sio4-168120:us-central1:db-skynet
  application:
    name: multi-tenant-app
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: false
  eureka:
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/